[package]
name = "crashpad"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
clipboard-win = "5.4.1"
drag = "2.1.1"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "gif", "webp", "bmp"] }
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2.11.6", features = ["protocol-asset"] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-global-shortcut = "2.3.2"
tauri-plugin-opener = "2.5.5"
tauri-plugin-single-instance = "2.4.5"
webview2-com = "0.38"
windows = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_System_LibraryLoader", "Win32_Graphics_Gdi", "Win32_System_Threading", "Win32_System_SystemInformation", "Win32_Graphics_Dxgi", "Win32_Storage_FileSystem", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_System_Power", "Win32_System_Registry", "Win32_System_WinRT", "Media_Control", "Foundation", "Foundation_Collections", "Storage_Streams", "Media_Ocr", "Graphics_Imaging", "Globalization", "Win32_Media_Audio", "Win32_Media_Audio_Endpoints", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant"] }

[build-dependencies]
tauri-build = "2.6.3"
